INSERT INTO users (username, full_name, password) VALUES 
('johndoe','John Doe','iodwihad18'),
('janedoe','Jane Doe','12dasdw'),
('mike123','Mike Johnson','d2wadd'),
('sarah_s','Sarah Smith','21ewda'),
('alice_92','Alice Brown','21edad'),
('tom_rock','Tom Williams','199duw98dh'),
('emily89','Emily Green','wdad1'),
('george22','George Taylor','koiaj89'),
('claire_97','Claire White','ijjawd'),
('andrew_h','Andrew Harris','pj8989y'),
('jessicaL','Jessica Lee','oidwahd1'),
('chris_k','Chris King','diaowdw2'),
('oliviaJ','Olivia Jones','dwiaod1'),
('matthewB','Matthew Brown','op89wd'),
('rachel_R','Rachel Roberts','plook9wd8'),
('nathanM','Nathan Moore','dojd92'),
('victoriaV','Victoria Vance','lolsiwd'),
('jasonW','Jason Williams','twhdwhuudwh'),
('emma_R','Emma Richards','asdwad'),
('tvuong','Derek Vuong','derekvuong');

INSERT INTO friends VALUES (username1, username2, accepted)
('John Doe', 'janedoe', FALSE),
('John Doe', 'mike123', FALSE),
('John Doe', 'sarah_s', FALSE),
('janedoe', 'mike123', FALSE),
('janedoe', 'alice_92', FALSE),
('mike123', 'sarah_s', FALSE),
('mike123', 'tom_rock', FALSE),
('sarah_s', 'emily89', FALSE),
('alice_92', 'george22', FALSE),
('alice_92', 'claire_97', FALSE),
('tom_rock', 'andrew_h', FALSE),
('emily89', 'jessicaL', FALSE),
('george22', 'chris_k', FALSE),
('claire_97', 'oliviaJ', FALSE),
('andrew_h', 'matthewB', FALSE),
('jessicaL', 'rachel_R', FALSE),
('chris_k', 'nathanM', FALSE),
('oliviaJ', 'victoriaV', FALSE),
('matthewB', 'jasonW', FALSE),
('rachel_R', 'emma_R', FALSE);
